menu:
  Home: /
  Archives: /archives
  Github: https://github.com/hopsken
  RSS: /atom.xml

favicon: /assets/hopsken.jpg
logo: /assets/hopsken.jpg

# 评论
# 多说
disqus: 
# gitment
gitment:
  enable: true
  github_id: 
  repo: 
  client_id: 
  client_secret: 